-- MAIN QUERY

                    IF OBJECT_ID('tempdb..#CFOP_INCIDENCIA') IS NOT NULL DROP TABLE #CFOP_INCIDENCIA;
                    IF OBJECT_ID('tempdb..#TMV_COM_IMPOSTOS') IS NOT NULL DROP TABLE #TMV_COM_IMPOSTOS;
                    IF OBJECT_ID('tempdb..#TMV_COM_INCIDENCIA_RECPAG') IS NOT NULL DROP TABLE #TMV_COM_INCIDENCIA_RECPAG;
                    IF OBJECT_ID('tempdb..#TMV_COM_INCIDENCIA_CFOP') IS NOT NULL DROP TABLE #TMV_COM_INCIDENCIA_CFOP;
                    IF OBJECT_ID('tempdb..#TMV_COM_INCIDENCIA_TMVFIXO') IS NOT NULL DROP TABLE #TMV_COM_INCIDENCIA_TMVFIXO;
                    IF OBJECT_ID('tempdb..#TMV_SUGERIDO_FINAL') IS NOT NULL DROP TABLE #TMV_SUGERIDO_FINAL;

                    CREATE TABLE #CFOP_INCIDENCIA (
                        COD_CFOP CHAR(5) COLLATE DATABASE_DEFAULT PRIMARY KEY
                    );

                    INSERT INTO #CFOP_INCIDENCIA (COD_CFOP) VALUES ('5101'),('5102'),('1101'),('1102');

                    SELECT COD_TIPO_MV INTO #TMV_COM_IMPOSTOS FROM TBIMPOSTOMVE WITH (NOLOCK) WHERE 1=1 AND COD_IMPOSTO IN ('IBSUF','IBSMUN','CBS') GROUP BY COD_TIPO_MV;
                    CREATE CLUSTERED INDEX IX_TEMP_IMPOSTOS ON #TMV_COM_IMPOSTOS (COD_TIPO_MV);

                    SELECT COD_TIPO_MV INTO #TMV_COM_INCIDENCIA_RECPAG FROM (
                        SELECT T.COD_TIPO_MV FROM #TMV_COM_IMPOSTOS IMP
                        INNER JOIN TBTIPOMVESTOQUE T WITH (NOLOCK) ON T.COD_TIPO_MV = IMP.COD_TIPO_MV WHERE 1=1 AND T.GERA_PAGAR_RECEBER IN ('R','P')
                    ) AS FonteDeIncidencia GROUP BY COD_TIPO_MV;
                    CREATE CLUSTERED INDEX IX_TEMP_INCIDENCIA ON #TMV_COM_INCIDENCIA_RECPAG (COD_TIPO_MV);

                    SELECT FonteTMVCFOPPrincipal.COD_TIPO_MV INTO #TMV_COM_INCIDENCIA_CFOP FROM (
                        SELECT FonteTMVCFOPAgrupados.COD_TIPO_MV, FonteTMVCFOPAgrupados.COD_CFOP, FonteTMVCFOPAgrupados.Qtde,
                            ROW_NUMBER() OVER (PARTITION BY FonteTMVCFOPAgrupados.COD_TIPO_MV ORDER BY FonteTMVCFOPAgrupados.Qtde DESC) AS Row
                        FROM (
                            SELECT FonteTMVCFOP.COD_TIPO_MV, FonteTMVCFOP.COD_CFOP, COUNT(FonteTMVCFOP.Num_item) Qtde FROM (
                                SELECT D.COD_TIPO_MV, DI.COD_CFOP COLLATE DATABASE_DEFAULT AS COD_CFOP, DI.Num_item FROM TBSAIDAS D WITH (NOLOCK)
                                INNER JOIN TBSAIDASITEM DI WITH (NOLOCK) ON DI.CHAVE_FATO = D.CHAVE_FATO
                                INNER JOIN #TMV_COM_IMPOSTOS IMP ON D.COD_TIPO_MV = IMP.COD_TIPO_MV WHERE 1=1 AND D.DATA_V1 >= '2026-01-01 00:00:00.000' AND ISNULL(D.STATUS,'') <> 'C' AND DI.COD_CFOP IS NOT NULL
                                UNION
                                SELECT D.COD_TIPO_MV, DI.COD_CFOP COLLATE DATABASE_DEFAULT AS COD_CFOP, DI.Num_item FROM TBENTRADAS D WITH (NOLOCK)
                                INNER JOIN TBENTRADASITEM DI WITH (NOLOCK) ON DI.CHAVE_FATO = D.CHAVE_FATO
                                INNER JOIN #TMV_COM_IMPOSTOS IMP ON D.COD_TIPO_MV = IMP.COD_TIPO_MV WHERE 1=1 AND D.DATA_V1 >= '2026-01-01 00:00:00.000' AND ISNULL(D.STATUS,'') <> 'C' AND DI.COD_CFOP IS NOT NULL
                            ) FonteTMVCFOP GROUP BY FonteTMVCFOP.COD_TIPO_MV, FonteTMVCFOP.COD_CFOP
                        ) FonteTMVCFOPAgrupados
                    ) FonteTMVCFOPPrincipal WHERE FonteTMVCFOPPrincipal.ROW = 1 AND FonteTMVCFOPPrincipal.COD_CFOP COLLATE DATABASE_DEFAULT IN (SELECT COD_CFOP COLLATE DATABASE_DEFAULT FROM #CFOP_INCIDENCIA) GROUP BY FonteTMVCFOPPrincipal.COD_TIPO_MV;
                    CREATE CLUSTERED INDEX IX_TEMP_INCIDENCIA ON #TMV_COM_INCIDENCIA_CFOP (COD_TIPO_MV);

                    SELECT T.COD_TIPO_MV INTO #TMV_COM_INCIDENCIA_TMVFIXO FROM TBTIPOMVESTOQUE T WITH (NOLOCK) INNER JOIN #TMV_COM_IMPOSTOS IMP ON T.COD_TIPO_MV = IMP.COD_TIPO_MV WHERE 1=1 AND ((LTRIM(RTRIM(T.CFOP_UF_PROD)) COLLATE DATABASE_DEFAULT IN (SELECT COD_CFOP COLLATE DATABASE_DEFAULT FROM #CFOP_INCIDENCIA)) OR (LTRIM(RTRIM(T.CFOP_UF_SERV)) COLLATE DATABASE_DEFAULT IN (SELECT COD_CFOP COLLATE DATABASE_DEFAULT FROM #CFOP_INCIDENCIA)));
                    CREATE CLUSTERED INDEX IX_TEMP_INCIDENCIA ON #TMV_COM_INCIDENCIA_TMVFIXO (COD_TIPO_MV);

                    SELECT IMP.COD_TIPO_MV, CAST(CASE WHEN ISNULL(ISNULL(INC_RECPAG.COD_TIPO_MV, INC_CFOP.COD_TIPO_MV), INC_TMV.COD_TIPO_MV) IS NOT NULL THEN 1 ELSE 2 END AS TINYINT) AS IND_INCIDENCIA_CBSIBS_SUGERIDO INTO #TMV_SUGERIDO_FINAL FROM #TMV_COM_IMPOSTOS AS IMP
                    LEFT JOIN #TMV_COM_INCIDENCIA_RECPAG AS INC_RECPAG ON IMP.COD_TIPO_MV = INC_RECPAG.COD_TIPO_MV
                    LEFT JOIN #TMV_COM_INCIDENCIA_CFOP AS INC_CFOP ON IMP.COD_TIPO_MV = INC_CFOP.COD_TIPO_MV
                    LEFT JOIN #TMV_COM_INCIDENCIA_TMVFIXO AS INC_TMV ON IMP.COD_TIPO_MV = INC_TMV.COD_TIPO_MV;
                    CREATE CLUSTERED INDEX IX_TEMP_SUGERIDO_FINAL ON #TMV_SUGERIDO_FINAL (COD_TIPO_MV);
                

SELECT * FROM (
                                    SELECT *,
                                           ROW_NUMBER() OVER (ORDER BY [CodTipoMv] ASC) AS RowNum
                                           , COUNT(*) OVER() AS TotalRegistros
                                    FROM (SELECT T.COD_TIPO_MV AS CodTipoMv, T.DESCRICAO AS Descricao, CAST(T.IND_INCIDENCIA_CBSIBS AS TINYINT) AS IndIncidenciaCBSIBS, S.IND_INCIDENCIA_CBSIBS_SUGERIDO AS IndIncidenciaCBSIBSSugerido FROM TBTIPOMVESTOQUE T WITH (NOLOCK) INNER JOIN #TMV_SUGERIDO_FINAL S ON S.COD_TIPO_MV = T.COD_TIPO_MV) Q
                                    WHERE 1=1  AND (T.COD_TIPO_MV LIKE @filtroLike COLLATE DATABASE_DEFAULT OR T.DESCRICAO LIKE @filtroLike COLLATE DATABASE_DEFAULT)
                                ) X
                                WHERE RowNum BETWEEN 1 AND 50

