FROM mcr.microsoft.com/mssql/server:2022-latest

USER root
CMD /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P "$MSSQL_SA_PASSWORD" -C -Q "IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'W1E1Core') BEGIN CREATE DATABASE W1E1Core; ALTER DATABASE W1E1Core SET COMPATIBILITY_LEVEL = 100; END"